<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd889fece2725be93bc17eea59fdc2384
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Conexao' => __DIR__ . '/../..' . '/model/conexao.class.php',
        'Config' => __DIR__ . '/../..' . '/model/Config.class.php',
        'Produtos' => __DIR__ . '/../..' . '/model/produtos.class.php',
        'Rotas' => __DIR__ . '/../..' . '/model/Rotas.class.php',
        'Template' => __DIR__ . '/../..' . '/model/Temple.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd889fece2725be93bc17eea59fdc2384::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd889fece2725be93bc17eea59fdc2384::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd889fece2725be93bc17eea59fdc2384::$classMap;

        }, null, ClassLoader::class);
    }
}
