<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Conexao' => $baseDir . '/model/conexao.class.php',
    'Config' => $baseDir . '/model/Config.class.php',
    'Produtos' => $baseDir . '/model/produtos.class.php',
    'Rotas' => $baseDir . '/model/Rotas.class.php',
    'Template' => $baseDir . '/model/Temple.class.php',
);
